// <auto-generated />
using System;
using AuctionWeb.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuctionWeb.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuctionWeb.Domain.Entities.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Item_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("AuctionWeb.Domain.Entities.AuctionBidding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuctionId")
                        .HasColumnType("int");

                    b.Property<int>("Auction_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("BidValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BidderId")
                        .HasColumnType("int");

                    b.Property<int>("Bidder_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("BiddingTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("BidderId");

                    b.ToTable("AuctionBiddings");
                });

            modelBuilder.Entity("AuctionWeb.Domain.Entities.Bidder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BidderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bidders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BidderName = "Abdo",
                            ContactName = "MR Abdo"
                        },
                        new
                        {
                            Id = 2,
                            BidderName = "Abdo2",
                            ContactName = "MR Abdo2"
                        },
                        new
                        {
                            Id = 3,
                            BidderName = "Abdo3",
                            ContactName = "MR Abdo3"
                        },
                        new
                        {
                            Id = 4,
                            BidderName = "Abdo4",
                            ContactName = "MR Abdo4"
                        },
                        new
                        {
                            Id = 5,
                            BidderName = "Abdo5",
                            ContactName = "MR Abdo5"
                        },
                        new
                        {
                            Id = 6,
                            BidderName = "Abdo6",
                            ContactName = "MR Abdo6"
                        });
                });

            modelBuilder.Entity("AuctionWeb.Domain.Entities.BidderAuction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuctionsId")
                        .HasColumnType("int");

                    b.Property<int?>("BiddersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuctionsId");

                    b.HasIndex("BiddersId");

                    b.ToTable("BidderAuctions");
                });

            modelBuilder.Entity("AuctionWeb.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemName = "Histrorical Watch",
                            Price = 10000m
                        },
                        new
                        {
                            Id = 2,
                            ItemName = "Histrorical Glass",
                            Price = 20000m
                        },
                        new
                        {
                            Id = 3,
                            ItemName = "Histrorical Sword",
                            Price = 50000m
                        },
                        new
                        {
                            Id = 4,
                            ItemName = "Histrorical Hat",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 5,
                            ItemName = "Histrorical Paint",
                            Price = 100000m
                        });
                });

            modelBuilder.Entity("AuctionWeb.Domain.Entities.Auction", b =>
                {
                    b.HasOne("AuctionWeb.Domain.Entities.Item", "Item")
                        .WithMany("Auctions")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("AuctionWeb.Domain.Entities.AuctionBidding", b =>
                {
                    b.HasOne("AuctionWeb.Domain.Entities.Auction", "Auction")
                        .WithMany()
                        .HasForeignKey("AuctionId");

                    b.HasOne("AuctionWeb.Domain.Entities.Bidder", "Bidder")
                        .WithMany()
                        .HasForeignKey("BidderId");
                });

            modelBuilder.Entity("AuctionWeb.Domain.Entities.BidderAuction", b =>
                {
                    b.HasOne("AuctionWeb.Domain.Entities.Auction", "Auctions")
                        .WithMany("Bidders")
                        .HasForeignKey("AuctionsId");

                    b.HasOne("AuctionWeb.Domain.Entities.Bidder", "Bidders")
                        .WithMany("Auctions")
                        .HasForeignKey("BiddersId");
                });
#pragma warning restore 612, 618
        }
    }
}
